/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/protected/admin/index'
import { Route as ProtectedMoviePaymentSucessRouteImport } from './routes/protected/movie/payment-sucess'
import { Route as ProtectedMoviePaymentSuccessRouteImport } from './routes/protected/movie/payment-success'
import { Route as ProtectedAdminScreenidSeatsRouteImport } from './routes/protected/admin/$screenid/seats'
import { Route as ProtectedUserProfileTicketidTicketRouteImport } from './routes/protected/user/profile/$ticketid/ticket'

const ProtectedAdminReportsLazyRouteImport = createFileRoute(
  '/protected/admin/reports',
)()
const ProtectedAdminAddLazyRouteImport = createFileRoute(
  '/protected/admin/add',
)()
const ProtectedUserProfileIndexLazyRouteImport = createFileRoute(
  '/protected/user/profile/',
)()
const ProtectedMovieMovieidIndexLazyRouteImport = createFileRoute(
  '/protected/movie/$movieid/',
)()
const ProtectedMovieMovieidPaymentLazyRouteImport = createFileRoute(
  '/protected/movie/$movieid/payment',
)()
const ProtectedAdminEditEditLazyRouteImport = createFileRoute(
  '/protected/admin/edit/$edit',
)()
const ProtectedAdminDeleteDeleteLazyRouteImport = createFileRoute(
  '/protected/admin/delete/$delete',
)()
const ProtectedUserProfileTicketidIndexLazyRouteImport = createFileRoute(
  '/protected/user/profile/$ticketid/',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/protected/admin/',
  path: '/protected/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminReportsLazyRoute =
  ProtectedAdminReportsLazyRouteImport.update({
    id: '/protected/admin/reports',
    path: '/protected/admin/reports',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/admin/reports.lazy').then((d) => d.Route),
  )
const ProtectedAdminAddLazyRoute = ProtectedAdminAddLazyRouteImport.update({
  id: '/protected/admin/add',
  path: '/protected/admin/add',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/protected/admin/add.lazy').then((d) => d.Route),
)
const ProtectedMoviePaymentSucessRoute =
  ProtectedMoviePaymentSucessRouteImport.update({
    id: '/protected/movie/payment-sucess',
    path: '/protected/movie/payment-sucess',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedMoviePaymentSuccessRoute =
  ProtectedMoviePaymentSuccessRouteImport.update({
    id: '/protected/movie/payment-success',
    path: '/protected/movie/payment-success',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedUserProfileIndexLazyRoute =
  ProtectedUserProfileIndexLazyRouteImport.update({
    id: '/protected/user/profile/',
    path: '/protected/user/profile/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/user/profile/index.lazy').then((d) => d.Route),
  )
const ProtectedMovieMovieidIndexLazyRoute =
  ProtectedMovieMovieidIndexLazyRouteImport.update({
    id: '/protected/movie/$movieid/',
    path: '/protected/movie/$movieid/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/movie/$movieid/index.lazy').then((d) => d.Route),
  )
const ProtectedMovieMovieidPaymentLazyRoute =
  ProtectedMovieMovieidPaymentLazyRouteImport.update({
    id: '/protected/movie/$movieid/payment',
    path: '/protected/movie/$movieid/payment',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/movie/$movieid/payment.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedAdminEditEditLazyRoute =
  ProtectedAdminEditEditLazyRouteImport.update({
    id: '/protected/admin/edit/$edit',
    path: '/protected/admin/edit/$edit',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/admin/edit/$edit.lazy').then((d) => d.Route),
  )
const ProtectedAdminDeleteDeleteLazyRoute =
  ProtectedAdminDeleteDeleteLazyRouteImport.update({
    id: '/protected/admin/delete/$delete',
    path: '/protected/admin/delete/$delete',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/admin/delete/$delete.lazy').then((d) => d.Route),
  )
const ProtectedAdminScreenidSeatsRoute =
  ProtectedAdminScreenidSeatsRouteImport.update({
    id: '/protected/admin/$screenid/seats',
    path: '/protected/admin/$screenid/seats',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedUserProfileTicketidIndexLazyRoute =
  ProtectedUserProfileTicketidIndexLazyRouteImport.update({
    id: '/protected/user/profile/$ticketid/',
    path: '/protected/user/profile/$ticketid/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/protected/user/profile/$ticketid/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ProtectedUserProfileTicketidTicketRoute =
  ProtectedUserProfileTicketidTicketRouteImport.update({
    id: '/protected/user/profile/$ticketid/ticket',
    path: '/protected/user/profile/$ticketid/ticket',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protected/movie/payment-success': typeof ProtectedMoviePaymentSuccessRoute
  '/protected/movie/payment-sucess': typeof ProtectedMoviePaymentSucessRoute
  '/protected/admin/add': typeof ProtectedAdminAddLazyRoute
  '/protected/admin/reports': typeof ProtectedAdminReportsLazyRoute
  '/protected/admin': typeof ProtectedAdminIndexRoute
  '/protected/admin/$screenid/seats': typeof ProtectedAdminScreenidSeatsRoute
  '/protected/admin/delete/$delete': typeof ProtectedAdminDeleteDeleteLazyRoute
  '/protected/admin/edit/$edit': typeof ProtectedAdminEditEditLazyRoute
  '/protected/movie/$movieid/payment': typeof ProtectedMovieMovieidPaymentLazyRoute
  '/protected/movie/$movieid': typeof ProtectedMovieMovieidIndexLazyRoute
  '/protected/user/profile': typeof ProtectedUserProfileIndexLazyRoute
  '/protected/user/profile/$ticketid/ticket': typeof ProtectedUserProfileTicketidTicketRoute
  '/protected/user/profile/$ticketid': typeof ProtectedUserProfileTicketidIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protected/movie/payment-success': typeof ProtectedMoviePaymentSuccessRoute
  '/protected/movie/payment-sucess': typeof ProtectedMoviePaymentSucessRoute
  '/protected/admin/add': typeof ProtectedAdminAddLazyRoute
  '/protected/admin/reports': typeof ProtectedAdminReportsLazyRoute
  '/protected/admin': typeof ProtectedAdminIndexRoute
  '/protected/admin/$screenid/seats': typeof ProtectedAdminScreenidSeatsRoute
  '/protected/admin/delete/$delete': typeof ProtectedAdminDeleteDeleteLazyRoute
  '/protected/admin/edit/$edit': typeof ProtectedAdminEditEditLazyRoute
  '/protected/movie/$movieid/payment': typeof ProtectedMovieMovieidPaymentLazyRoute
  '/protected/movie/$movieid': typeof ProtectedMovieMovieidIndexLazyRoute
  '/protected/user/profile': typeof ProtectedUserProfileIndexLazyRoute
  '/protected/user/profile/$ticketid/ticket': typeof ProtectedUserProfileTicketidTicketRoute
  '/protected/user/profile/$ticketid': typeof ProtectedUserProfileTicketidIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protected/movie/payment-success': typeof ProtectedMoviePaymentSuccessRoute
  '/protected/movie/payment-sucess': typeof ProtectedMoviePaymentSucessRoute
  '/protected/admin/add': typeof ProtectedAdminAddLazyRoute
  '/protected/admin/reports': typeof ProtectedAdminReportsLazyRoute
  '/protected/admin/': typeof ProtectedAdminIndexRoute
  '/protected/admin/$screenid/seats': typeof ProtectedAdminScreenidSeatsRoute
  '/protected/admin/delete/$delete': typeof ProtectedAdminDeleteDeleteLazyRoute
  '/protected/admin/edit/$edit': typeof ProtectedAdminEditEditLazyRoute
  '/protected/movie/$movieid/payment': typeof ProtectedMovieMovieidPaymentLazyRoute
  '/protected/movie/$movieid/': typeof ProtectedMovieMovieidIndexLazyRoute
  '/protected/user/profile/': typeof ProtectedUserProfileIndexLazyRoute
  '/protected/user/profile/$ticketid/ticket': typeof ProtectedUserProfileTicketidTicketRoute
  '/protected/user/profile/$ticketid/': typeof ProtectedUserProfileTicketidIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/protected/movie/payment-success'
    | '/protected/movie/payment-sucess'
    | '/protected/admin/add'
    | '/protected/admin/reports'
    | '/protected/admin'
    | '/protected/admin/$screenid/seats'
    | '/protected/admin/delete/$delete'
    | '/protected/admin/edit/$edit'
    | '/protected/movie/$movieid/payment'
    | '/protected/movie/$movieid'
    | '/protected/user/profile'
    | '/protected/user/profile/$ticketid/ticket'
    | '/protected/user/profile/$ticketid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/protected/movie/payment-success'
    | '/protected/movie/payment-sucess'
    | '/protected/admin/add'
    | '/protected/admin/reports'
    | '/protected/admin'
    | '/protected/admin/$screenid/seats'
    | '/protected/admin/delete/$delete'
    | '/protected/admin/edit/$edit'
    | '/protected/movie/$movieid/payment'
    | '/protected/movie/$movieid'
    | '/protected/user/profile'
    | '/protected/user/profile/$ticketid/ticket'
    | '/protected/user/profile/$ticketid'
  id:
    | '__root__'
    | '/'
    | '/protected/movie/payment-success'
    | '/protected/movie/payment-sucess'
    | '/protected/admin/add'
    | '/protected/admin/reports'
    | '/protected/admin/'
    | '/protected/admin/$screenid/seats'
    | '/protected/admin/delete/$delete'
    | '/protected/admin/edit/$edit'
    | '/protected/movie/$movieid/payment'
    | '/protected/movie/$movieid/'
    | '/protected/user/profile/'
    | '/protected/user/profile/$ticketid/ticket'
    | '/protected/user/profile/$ticketid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedMoviePaymentSuccessRoute: typeof ProtectedMoviePaymentSuccessRoute
  ProtectedMoviePaymentSucessRoute: typeof ProtectedMoviePaymentSucessRoute
  ProtectedAdminAddLazyRoute: typeof ProtectedAdminAddLazyRoute
  ProtectedAdminReportsLazyRoute: typeof ProtectedAdminReportsLazyRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminScreenidSeatsRoute: typeof ProtectedAdminScreenidSeatsRoute
  ProtectedAdminDeleteDeleteLazyRoute: typeof ProtectedAdminDeleteDeleteLazyRoute
  ProtectedAdminEditEditLazyRoute: typeof ProtectedAdminEditEditLazyRoute
  ProtectedMovieMovieidPaymentLazyRoute: typeof ProtectedMovieMovieidPaymentLazyRoute
  ProtectedMovieMovieidIndexLazyRoute: typeof ProtectedMovieMovieidIndexLazyRoute
  ProtectedUserProfileIndexLazyRoute: typeof ProtectedUserProfileIndexLazyRoute
  ProtectedUserProfileTicketidTicketRoute: typeof ProtectedUserProfileTicketidTicketRoute
  ProtectedUserProfileTicketidIndexLazyRoute: typeof ProtectedUserProfileTicketidIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/admin/': {
      id: '/protected/admin/'
      path: '/protected/admin'
      fullPath: '/protected/admin'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/admin/reports': {
      id: '/protected/admin/reports'
      path: '/protected/admin/reports'
      fullPath: '/protected/admin/reports'
      preLoaderRoute: typeof ProtectedAdminReportsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/admin/add': {
      id: '/protected/admin/add'
      path: '/protected/admin/add'
      fullPath: '/protected/admin/add'
      preLoaderRoute: typeof ProtectedAdminAddLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/movie/payment-sucess': {
      id: '/protected/movie/payment-sucess'
      path: '/protected/movie/payment-sucess'
      fullPath: '/protected/movie/payment-sucess'
      preLoaderRoute: typeof ProtectedMoviePaymentSucessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/movie/payment-success': {
      id: '/protected/movie/payment-success'
      path: '/protected/movie/payment-success'
      fullPath: '/protected/movie/payment-success'
      preLoaderRoute: typeof ProtectedMoviePaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/user/profile/': {
      id: '/protected/user/profile/'
      path: '/protected/user/profile'
      fullPath: '/protected/user/profile'
      preLoaderRoute: typeof ProtectedUserProfileIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/movie/$movieid/': {
      id: '/protected/movie/$movieid/'
      path: '/protected/movie/$movieid'
      fullPath: '/protected/movie/$movieid'
      preLoaderRoute: typeof ProtectedMovieMovieidIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/movie/$movieid/payment': {
      id: '/protected/movie/$movieid/payment'
      path: '/protected/movie/$movieid/payment'
      fullPath: '/protected/movie/$movieid/payment'
      preLoaderRoute: typeof ProtectedMovieMovieidPaymentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/admin/edit/$edit': {
      id: '/protected/admin/edit/$edit'
      path: '/protected/admin/edit/$edit'
      fullPath: '/protected/admin/edit/$edit'
      preLoaderRoute: typeof ProtectedAdminEditEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/admin/delete/$delete': {
      id: '/protected/admin/delete/$delete'
      path: '/protected/admin/delete/$delete'
      fullPath: '/protected/admin/delete/$delete'
      preLoaderRoute: typeof ProtectedAdminDeleteDeleteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/admin/$screenid/seats': {
      id: '/protected/admin/$screenid/seats'
      path: '/protected/admin/$screenid/seats'
      fullPath: '/protected/admin/$screenid/seats'
      preLoaderRoute: typeof ProtectedAdminScreenidSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/user/profile/$ticketid/': {
      id: '/protected/user/profile/$ticketid/'
      path: '/protected/user/profile/$ticketid'
      fullPath: '/protected/user/profile/$ticketid'
      preLoaderRoute: typeof ProtectedUserProfileTicketidIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/user/profile/$ticketid/ticket': {
      id: '/protected/user/profile/$ticketid/ticket'
      path: '/protected/user/profile/$ticketid/ticket'
      fullPath: '/protected/user/profile/$ticketid/ticket'
      preLoaderRoute: typeof ProtectedUserProfileTicketidTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedMoviePaymentSuccessRoute: ProtectedMoviePaymentSuccessRoute,
  ProtectedMoviePaymentSucessRoute: ProtectedMoviePaymentSucessRoute,
  ProtectedAdminAddLazyRoute: ProtectedAdminAddLazyRoute,
  ProtectedAdminReportsLazyRoute: ProtectedAdminReportsLazyRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminScreenidSeatsRoute: ProtectedAdminScreenidSeatsRoute,
  ProtectedAdminDeleteDeleteLazyRoute: ProtectedAdminDeleteDeleteLazyRoute,
  ProtectedAdminEditEditLazyRoute: ProtectedAdminEditEditLazyRoute,
  ProtectedMovieMovieidPaymentLazyRoute: ProtectedMovieMovieidPaymentLazyRoute,
  ProtectedMovieMovieidIndexLazyRoute: ProtectedMovieMovieidIndexLazyRoute,
  ProtectedUserProfileIndexLazyRoute: ProtectedUserProfileIndexLazyRoute,
  ProtectedUserProfileTicketidTicketRoute:
    ProtectedUserProfileTicketidTicketRoute,
  ProtectedUserProfileTicketidIndexLazyRoute:
    ProtectedUserProfileTicketidIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
